[[navbar]]
identifier = "demos"
name = "Demos"
url = "/en/demos/"
weight = 1

[[navbar]]
identifier = "thhar"
name = "Thhar, a 3d rendering engine"
url = "/en/demos/"
parent = "demos"

[[navbar]]
identifier = "cube3d"
name = "A 3d cube"
url = "/en/demos/basic"
parent = "thhar"

[[navbar]]
identifier = "Scolors"
name = "Colorful cubes"
url = "/en/demos/colors"
parent = "thhar"

[[navbar]]
identifier = "teapot"
name = "Sequenced cameras"
url = "/en/demos/sequence"
parent = "thhar"

[[navbar]]
identifier = "animation"
name = "3D animation"
url = "/en/demos/animation"
parent = "thhar"


[[navbar]]
identifier = "posts"
name = "Posts"
url = "/en/posts"

[[navbar]]
identifier = "about"
name = "About"
url = "/en/about"
