[[navbar]]
identifier = "demos"
name = "Dema"
url = "/en/demos/"
weight = 1

[[navbar]]
identifier = "thhar"
name = "Thhar, silnik 3D"
url = "/pl/demos/"
parent = "demos"

[[navbar]]
identifier = "cube3d"
name = "Kostka w 3D"
url = "/en/demos/basic"
parent = "thhar"

[[navbar]]
identifier = "Scolors"
name = "Kolorowe Kostki"
url = "/en/demos/colors"
parent = "thhar"

[[navbar]]
identifier = "teapot"
name = "Sekfencja Kamer - Imbryk"
url = "/en/demos/sequence"
parent = "thhar"

[[navbar]]
identifier = "animation"
name = "3D animacja"
url = "/en/demos/animation"
parent = "thhar"


[[navbar]]
identifier = "posts"
name = "Posty"
url = "/pl/posts"

[[navbar]]
identifier = "about"
name = "O mnie"
url = "/pl/about"
